declare module '@kangc/v-md-editor'
declare module '@kangc/v-md-editor/lib/theme/vuepress.js'
declare module '@kangc/v-md-editor/lib/theme/github.js'
declare module 'prismjs'
declare module '@kangc/v-md-editor/lib/plugins/mermaid/cdn.js'
declare module '@kangc/v-md-editor/lib/codemirror-editor'
declare module 'codemirror'
